ARG version
ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Sam" \
    DURATION="10HRS" \
    AUTHOR="devops"
RUN echo "Trainer is: ${TRAINER}, version is: ${version}"
CMD ["sleep", "200"]